### ISSUE TITLE
Any build on the way?

### ISSUE THREAD

**Issue by anonimno1** [krzysztofsroga/Libre-Home-Android#4]
Hi,

whats up? Hope you and your family are fine!
I have been using the 0.4 for a couple of weeks now and it works nice. SSH os not working at all and the multiple value switches mostly do not work also. But not a big issue, app is still usable.
Are you working on somerhing new?

Regards
K

**Comment by krzysztofsroga** [comment]
Hi,
due to the epidemic, I have less time to work on my projects. I'm trying to help wherever it is possible.
 I think the development will slow down a bit until it is over. 
But it won't stop totally! I have recently changed my laptop and have moved all of the things. I have a few changes already in testing, I'll upload and build them in a few days(possibly Thursday). I know about the SSH issue, it stopped working for me too.

**Comment by krzysztofsroga** [comment]
Hi,
due to the epidemic, I have less time to work on my projects. I'm trying to help wherever it is possible.
 I think the development will slow down a bit until it is over. 
But it won't stop totally! I have recently changed my laptop and have moved all of the things. I have a few changes already in testing, I'll upload and build them in a few days(possibly Thursday). I know about the SSH issue, it stopped working for me too.

**Comment by anonimno1** [comment]
Great!
Wish you and your family all the good in this crazy time.
